version: "2"

networks:
  default:
    external:
      name: net_test

services:
  # simple-rest:
  #   build: ../
  #   image: simple-rest:2.0
  #   restart: always
  #   container_name: simple-rest
  #   ports:
  #     - "8085:8085"

  mongodb:
    image: mongo:latest
    container_name: "simple-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
